name: CI

on: [push]

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: jjst/java-jsonpath-api:latest
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        run: |
          docker build -t $IMAGE_NAME .
      - name: Test image runs
        run: |
          docker run --name test-container --rm -d $IMAGE_NAME
          docker top test-container
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: |
          docker push $IMAGE_NAME
  deploy:
    name: Deploy
    needs: build-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: jjst/digitalocean-deploy-app@v0.8
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          application-id: 23442bf3-3bc5-4c9c-80af-47c34ec2e4d9
